plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.junit.jupiter:junit-jupiter:5.9.3")
    testImplementation ("org.slf4j:slf4j-simple:2.0.17")
    implementation("com.codeborne:selenide:7.9.4")
    implementation("org.assertj:assertj-core:3.27.7")
    implementation ("com.github.javafaker:javafaker:1.0.2")
}


test {
    useJUnitPlatform()
}
